name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  normal-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install libpcap-dev -qq
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Gems
      run: |
        bundle config set path 'vendor/bundle'
        bundle config set --local without noci rubocop
        bundle install
    - name: Run parsing/generating tests
      run: bundle exec rake

  cap-inj-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install libpcap-dev -qq
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: |
        sudo gem install bundler --no-document
        sudo bundle config set path 'vendor/bundle'
        sudo bundle config set --local without noci
        sudo bundle install
    - name: Run capture and injection tests
      run: sudo bundle exec rake spec:sudo
