# pulled from repo
name: "Rubocop"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  #schedule:
  #  - cron: '39 15 * * 4'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Ruby 2.4
        ruby-version: 2.4

    - name: Set up Bundler
      run: |
        gem install bundler -v '= 2.2.15'
        bundle _2.2.15_ config path vendor/bundle
        bundle _2.2.15_ config set --local without noci

    # This step is not necessary if you add the gem to your Gemfile
    # Ruby 2.4: limit rubocop-performance to 1.10.2 max
    - name: Install Code Scanning integration
      run: |
        bundle _2.2.15_ add code-scanning-rubocop --version '= 0.5.0' --source 'https://rubygems.org' --skip-install
        bundle _2.2.15_ add rubocop-performance --version '=1.10.2' --source 'https://rubygems.org' --skip-install

    - name: Install dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install libpcap-dev -qq
        bundle _2.2.15_ install

    - name: Rubocop run
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif lib/
          [[ $? -ne 2 ]]
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rubocop.sarif
